spring:
  application:
    name: notification
  cloud:
    function:
      definition: orderConfirmEventConsumer
    stream:
      function:
        definition: orderConfirmEventConsumer
      bindings:
        orderConfirmEventConsumer-in-0:
          destination: order.exchange.new
          group: notification-group
          content-type: application/json
      kafka:
        binder:
            brokers: localhost:9092
#  rabbitmq:
#    host: ${RABBITMQ_HOST:localhost}
#    port: ${RABBITMQ_PORT:5672}
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    virtual-host: ${RABBITMQ_VHOST:/}
#    connection-timeout: 30000

server:
  port: 8084

#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking
