
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/phucnguyen/udemy_Microservice_Embark/practiceCode/Ecom-Microservice-Modules/configserver/src/main/resources/config
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 30000

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
